# configuraciones_maestras.urls.py
from django.urls import path
from .views import (
    home_maestras,
    lista_proveedores,
    lista_agentes_transporte,
    lista_despachantes_aduana,
    lista_tasas_cambio,
    agregar_proveedor,
    editar_proveedor,
    eliminar_proveedor,
    detalle_proveedor,
    inactivar_proveedor,
    agregar_agente_transporte,
    editar_agente_transporte,
    eliminar_agente_transporte,
    detalle_agente_transporte,
    agregar_despachante_aduana,
    editar_despachante_aduana,
    eliminar_despachante_aduana,
    detalle_despachante_aduana,
    agregar_tasa_cambio,
    editar_tasa_cambio,
    eliminar_tasa_cambio,
    detalle_tasa_cambio,
)

urlpatterns = [
    #path('', home_maestras, name='home_maestras'),
    path('proveedores/', lista_proveedores, name='lista_proveedores'),
    
    #path('despachantes-aduana/', lista_despachantes_aduana, name='lista_despachantes_aduana'),
    #path('tasas-cambio/', lista_tasas_cambio, name='lista_tasas_cambio'),
    path('proveedores/agregar/', agregar_proveedor, name='agregar_proveedor'),
    path('proveedores/editar/<int:pk>/', editar_proveedor, name='editar_proveedor'),
    path('proveedores/inactivar/<int:pk>/', inactivar_proveedor, name='inactivar_proveedor'),
    #path('proveedores/eliminar/<int:pk>/', eliminar_proveedor, name='eliminar_proveedor'),
    path('proveedores/detalle/<int:pk>/', detalle_proveedor, name='detalle_proveedor'),
    
    path('agentes-transporte/', lista_agentes_transporte, name='lista_agentes_transporte'),
    path('agentes-transporte/agregar/', agregar_agente_transporte, name='agregar_agente_transporte'),
    #path('agentes-transporte/editar/<int:pk>/', editar_agente_transporte, name='editar_agente_transporte'),
    #path('agentes-transporte/eliminar/<int:pk>/', eliminar_agente_transporte, name='eliminar_agente_transporte'),
    path('agentes-transporte/detalle/<int:pk>/', detalle_agente_transporte, name='detalle_agente_transporte'),
    #path('despachantes-aduana/agregar/', agregar_despachante_aduana, name='agregar_despachante_aduana'),
    #path('despachantes-aduana/editar/<int:pk>/', editar_despachante_aduana, name='editar_despachante_aduana'),
    #path('despachantes-aduana/eliminar/<int:pk>/', eliminar_despachante_aduana, name='eliminar_despachante_aduana'),
    #path('despachantes-aduana/detalle/<int:pk>/', detalle_despachante_aduana, name='detalle_despachante_aduana'),
    #path('tasas-cambio/agregar/', agregar_tasa_cambio, name='agregar_tasa_cambio'),
    #path('tasas-cambio/editar/<int:pk>/', editar_tasa_cambio, name='editar_tasa_cambio'),
    #path('tasas-cambio/eliminar/<int:pk>/', eliminar_tasa_cambio, name='eliminar_tasa_cambio'),
    #path('tasas-cambio/detalle/<int:pk>/', detalle_tasa_cambio, name='detalle_tasa_cambio'),
]
