# Generated by Django 5.2.5 on 2025-09-12 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuraciones_maestras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Depósito')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación del Depósito')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Adicional')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Unidad')),
                ('abreviatura', models.CharField(max_length=10, unique=True, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Vehículo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('año', models.PositiveIntegerField(verbose_name='Año de Fabricación')),
                ('kilometraje', models.PositiveIntegerField(default=0, verbose_name='Kilometraje')),
                ('codigo_chasis', models.CharField(max_length=50, unique=True, verbose_name='Código de Chasis (VIN)')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('mantenimiento', 'En Mantenimiento'), ('reservado', 'Reservado')], default='disponible', max_length=20, verbose_name='Estado')),
                ('costo_compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo de Compra (Guaraníes)')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de Venta Sugerido')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso al Inventario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Repuesto')),
                ('codigo_repuesto', models.CharField(max_length=50, unique=True, verbose_name='Código del Repuesto')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock Actual')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo')),
                ('costo_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Compra (Guaraníes)')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Venta Sugerido')),
                ('fecha_ultima_entrada', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Entrada')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Adicional')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones_maestras.proveedor', verbose_name='Proveedor')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.unidadmedida', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SalidaRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Salida')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Salida')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo de la Salida')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='inventario.repuesto')),
            ],
            options={
                'verbose_name': 'Salida de Repuesto',
                'verbose_name_plural': 'Salidas de Repuestos',
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField(verbose_name='Fecha de Mantenimiento')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo del Mantenimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Adicional')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventario.vehiculo')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Vehículo',
                'verbose_name_plural': 'Mantenimientos de Vehículos',
                'ordering': ['-fecha_mantenimiento'],
            },
        ),
    ]
