# Generated by Django 5.2.5 on 2025-09-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacidad Máxima (unidades)'),
        ),
        migrations.AddField(
            model_name='deposito',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='mantenimientovehiculo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='mantenimientovehiculo',
            name='estado_mantenimiento',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20, verbose_name='Estado del Mantenimiento'),
        ),
        migrations.AddField(
            model_name='mantenimientovehiculo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Ingreso al Inventario'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('vehiculo', 'Vehículo'), ('repuesto', 'Repuesto')], max_length=20, null=True, verbose_name='Tipo de Producto'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación en el Depósito'),
        ),
        migrations.AddField(
            model_name='salidarepuesto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Adicional'),
        ),
        migrations.AddField(
            model_name='salidarepuesto',
            name='tipo_salida',
            field=models.CharField(choices=[('venta', 'Venta'), ('uso_interno', 'Uso Interno'), ('devolucion', 'Devolución'), ('otro', 'Otro')], default='venta', max_length=20, verbose_name='Tipo de Salida'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Adicional'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('vehiculo', 'Vehículo'), ('repuesto', 'Repuesto')], max_length=20, null=True, verbose_name='Tipo de Producto'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación en el Depósito'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Ingreso al Inventario'),
        ),
    ]
