# Generated by Django 6.0.2 on 2026-04-03 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_deposito_capacidad_maxima_deposito_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría del Repuesto'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='compatibilidad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Compatibilidad (Modelos/Marcas)'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Unitario (Guaraníes)'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(blank=True, choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido'), ('otro', 'Otro')], default='gasolina', max_length=50, null=True, verbose_name='Tipo de Combustible'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='motorizacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motorización'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='precio_cif_guarani',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio CIF (Guaraníes)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='precio_cif_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio CIF (USD)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Transmisión'),
        ),
        migrations.CreateModel(
            name='CentroVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Centro de Ventas')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección del Centro de Ventas')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico de Contacto')),
                ('gerente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Gerente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_ventas', to='inventario.deposito', verbose_name='Depósito Asociado')),
            ],
            options={
                'verbose_name': 'Centro de Ventas',
                'verbose_name_plural': 'Centros de Ventas',
                'ordering': ['nombre'],
            },
        ),
    ]
