# Generated by Django 6.0.2 on 2026-04-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_repuesto_categoria_repuesto_compatibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientovehiculo',
            name='repuestos_utilizados',
            field=models.ManyToManyField(blank=True, to='inventario.repuesto', verbose_name='Repuestos Utilizados'),
        ),
    ]
