# Generated by Django 5.2.5 on 2025-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tiene_usuario',
            field=models.BooleanField(default=False, verbose_name='Tiene Usuario'),
        ),
    ]
