# Generated by Django 5.2.5 on 2025-09-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_usuarios', '0002_empleado_tiene_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='codename',
            field=models.CharField(default='sin_codename', max_length=100, unique=True),
        ),
    ]
