# Generated by Django 6.0.2 on 2026-02-27 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones_maestras', '0003_departamento_cargo'),
        ('seguridad_usuarios', '0003_permiso_codename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['codename'], 'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_terminacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Terminación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='configuraciones_maestras.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='configuraciones_maestras.departamento', verbose_name='Departamento'),
        ),
    ]
