# Generated by Django 6.0.2 on 2026-04-03 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0003_repuesto_categoria_repuesto_compatibilidad_and_more'),
        ('seguridad_usuarios', '0004_alter_permiso_options_empleado_fecha_contratacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudReposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('enviada', 'Enviada para Consolidación'), ('consolidada', 'Consolidada en Importación'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='generada', max_length=20, verbose_name='Estado de la Solicitud')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_creadas', to='seguridad_usuarios.usuarioperfil')),
                ('usuario_finalizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_finalizadas', to='seguridad_usuarios.usuarioperfil')),
            ],
            options={
                'verbose_name': 'Solicitud de Reposición',
                'verbose_name_plural': 'Solicitudes de Reposición',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('vehiculo', 'Vehículo'), ('repuesto', 'Repuesto')], default='repuesto', max_length=20, verbose_name='Tipo de Ítem')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Solicitada')),
                ('comentario_item', models.TextField(blank=True, null=True, verbose_name='Comentario del Ítem')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unitario')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Unitario')),
                ('repuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.repuesto')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.vehiculo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_solicitados', to='reposicion_stock.solicitudreposicion')),
            ],
            options={
                'verbose_name': 'Ítem de Solicitud',
                'verbose_name_plural': 'Ítems de Solicitud',
            },
        ),
    ]
