# Generated by Django 6.0.2 on 2026-04-03 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_pedidos', '0001_initial'),
        ('inventario', '0003_repuesto_categoria_repuesto_compatibilidad_and_more'),
        ('seguridad_usuarios', '0004_alter_permiso_options_empleado_fecha_contratacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='clientes_pedidos.cliente')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.CreateModel(
            name='CarritoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carritos_vendedor', to='clientes_pedidos.cliente')),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_vendedor', to='seguridad_usuarios.empleado')),
            ],
            options={
                'verbose_name': 'Carrito del Vendedor',
                'verbose_name_plural': 'Carritos de los Vendedores',
            },
        ),
        migrations.CreateModel(
            name='HistorialCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_compras', to='clientes_pedidos.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_compras', to='clientes_pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Historial de Compra',
                'verbose_name_plural': 'Historiales de Compras',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='ItemCarritoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_pedidos.carrito')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.repuesto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='repuestos',
            field=models.ManyToManyField(through='clientes_pedidos.ItemCarritoRepuesto', to='inventario.repuesto'),
        ),
        migrations.CreateModel(
            name='ItemCarritoRepuestoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_pedidos.carritovendedor')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.repuesto')),
            ],
        ),
        migrations.AddField(
            model_name='carritovendedor',
            name='repuestos',
            field=models.ManyToManyField(through='clientes_pedidos.ItemCarritoRepuestoVendedor', to='inventario.repuesto'),
        ),
        migrations.CreateModel(
            name='ItemCarritoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_pedidos.carrito')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='vehiculos',
            field=models.ManyToManyField(through='clientes_pedidos.ItemCarritoVehiculo', to='inventario.vehiculo'),
        ),
        migrations.CreateModel(
            name='ItemCarritoVehiculoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_pedidos.carritovendedor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='carritovendedor',
            name='vehiculos',
            field=models.ManyToManyField(through='clientes_pedidos.ItemCarritoVehiculoVendedor', to='inventario.vehiculo'),
        ),
    ]
