# Generated by Django 5.2.5 on 2025-09-12 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_origen', models.CharField(default='KRW', max_length=3, verbose_name='Moneda de Origen')),
                ('moneda_destino', models.CharField(default='PYG', max_length=3, verbose_name='Moneda de Destino')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor de la Tasa')),
                ('fecha_actualizacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='AgenteTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('FISICA', 'Persona Física'), ('JURIDICA', 'Persona Jurídica')], default='FISICA', max_length=10, verbose_name='Tipo de Persona')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos')),
                ('ruc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RUC o Identificador Fiscal')),
                ('documento_identidad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento de Identidad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_agente_transporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agente de Transporte',
                'verbose_name_plural': 'Agentes de Transporte',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DespachanteAduana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('FISICA', 'Persona Física'), ('JURIDICA', 'Persona Jurídica')], default='FISICA', max_length=10, verbose_name='Tipo de Persona')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('apellidos', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos')),
                ('ruc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RUC o Identificador Fiscal')),
                ('documento_identidad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento de Identidad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Despachante')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('registro', models.CharField(max_length=50, unique=True, verbose_name='Número de Registro')),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_despachante_aduana', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despachante de Aduana',
                'verbose_name_plural': 'Despachantes de Aduana',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('FISICA', 'Persona Física'), ('JURIDICA', 'Persona Jurídica')], default='FISICA', max_length=10, verbose_name='Tipo de Persona')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos')),
                ('ruc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RUC o Identificador Fiscal')),
                ('documento_identidad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento de Identidad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_proveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
