# Generated by Django 5.2.5 on 2025-09-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones_maestras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentetransporte',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto'),
        ),
    ]
