# Generated by Django 6.0.2 on 2026-04-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones_maestras', '0003_departamento_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionApariencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('theme-default', 'Azul Profesional (Defecto)'), ('theme-dark', 'Modo Oscuro'), ('theme-emerald', 'Esmeralda Energético')], default='theme-default', max_length=40, verbose_name='Tema')),
                ('tipografia', models.CharField(choices=[("'Roboto', sans-serif", 'Roboto'), ("'Playfair Display', serif", 'Elegante (Serif)'), ('monospace', 'Sistema (Monospace)')], default="'Roboto', sans-serif", max_length=100, verbose_name='Tipografía')),
                ('tamanio', models.PositiveSmallIntegerField(default=16, verbose_name='Tamaño de texto (px)')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Configuración de Apariencia',
                'verbose_name_plural': 'Configuraciones de Apariencia',
            },
        ),
    ]
