# Generated by Django 6.0.2 on 2026-04-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones_maestras', '0005_alter_configuracionapariencia_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionapariencia',
            name='tema',
            field=models.CharField(choices=[('theme-default', 'Azul Profesional (Defecto)'), ('theme-dark', 'Modo Oscuro'), ('theme-emerald', 'Esmeralda Energético'), ('theme-sunset', 'Atardecer Cálido'), ('theme-ocean', 'Océano Profundo'), ('theme-light', 'Tema Luminoso')], default='theme-default', max_length=40, verbose_name='Tema'),
        ),
    ]
